framework:
  test: true

services:
  _defaults:
    autoconfigure: true
    autowire: true

  Doctrine\ORM\EntityManagerInterface:
    alias: Doctrine\ORM\EntityManager
    public: true

  doctrine.orm.entity_manager:
    alias: Doctrine\ORM\EntityManager
    public: true

  Anunde\Tests\:
    resource: '../../../tests'

  # Instance selector
  Anunde\Api\User\Domain\Service\IJWTEncoderService: '@Anunde\Tests\Api\User\Infrastructure\Service\ConstantJWTEncoderService'