framework:
  test: true

services:
  _defaults:
    autoconfigure: true
    autowire: true

  Anunde\Tests\:
    resource: '../../../tests'

  # Instance selector
  Anunde\Api\User\Domain\Service\IJWTEncoder: '@Anunde\Tests\Api\User\Infrastructure\Service\ConstantJWTEncoderService'