<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV9sJ9fF\Anunde_Apps_Api_ApiKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV9sJ9fF/Anunde_Apps_Api_ApiKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV9sJ9fF.legacy');

    return;
}

if (!\class_exists(Anunde_Apps_Api_ApiKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV9sJ9fF\Anunde_Apps_Api_ApiKernelDevDebugContainer::class, Anunde_Apps_Api_ApiKernelDevDebugContainer::class, false);
}

return new \ContainerV9sJ9fF\Anunde_Apps_Api_ApiKernelDevDebugContainer([
    'container.build_hash' => 'V9sJ9fF',
    'container.build_id' => 'a845b3a8',
    'container.build_time' => 1737026652,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV9sJ9fF');
