<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpNKcdh\Anunde_Apps_Api_ApiKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpNKcdh/Anunde_Apps_Api_ApiKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXpNKcdh.legacy');

    return;
}

if (!\class_exists(Anunde_Apps_Api_ApiKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXpNKcdh\Anunde_Apps_Api_ApiKernelDevDebugContainer::class, Anunde_Apps_Api_ApiKernelDevDebugContainer::class, false);
}

return new \ContainerXpNKcdh\Anunde_Apps_Api_ApiKernelDevDebugContainer([
    'container.build_hash' => 'XpNKcdh',
    'container.build_id' => '57ba68b1',
    'container.build_time' => 1737447554,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXpNKcdh');
