<?php

namespace ContainerV9sJ9fF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginControllerService extends Anunde_Apps_Api_ApiKernelDevDebugContainer
{
    /**
     * Gets the public 'Anunde\Apps\Api\Controller\LoginController' shared autowired service.
     *
     * @return \Anunde\Apps\Api\Controller\LoginController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/LoginController.php';
        include_once \dirname(__DIR__, 6).'/src/Api/User/Application/UserLogger/UserLoggerCommandHandler.php';
        include_once \dirname(__DIR__, 6).'/src/Shared/Infrastructure/Persistence/Doctrine/DoctrineRepository.php';
        include_once \dirname(__DIR__, 6).'/src/Api/User/Domain/Repository/IUserRepository.php';
        include_once \dirname(__DIR__, 6).'/src/Api/User/Infrastructure/Persistence/DoctrineUserRepository.php';
        include_once \dirname(__DIR__, 6).'/src/Api/User/Domain/Service/IJWTEncoderService.php';
        include_once \dirname(__DIR__, 6).'/src/Api/User/Infrastructure/Service/JWTEncoderService.php';
        include_once \dirname(__DIR__, 6).'/src/Api/User/Domain/Service/IPasswordEncoder.php';
        include_once \dirname(__DIR__, 6).'/src/Api/User/Infrastructure/Service/PasswordEncoderService.php';

        $container->services['Anunde\\Apps\\Api\\Controller\\LoginController'] = $instance = new \Anunde\Apps\Api\Controller\LoginController(new \Anunde\Api\User\Application\UserLogger\UserLoggerCommandHandler(new \Anunde\Api\User\Infrastructure\Persistence\DoctrineUserRepository(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'))), new \Anunde\Api\User\Infrastructure\Service\JWTEncoderService(($container->services['lexik_jwt_authentication.encoder'] ?? $container->load('getLexikJwtAuthentication_EncoderService'))), new \Anunde\Api\User\Infrastructure\Service\PasswordEncoderService()));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'security.authorization_checker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'security.csrf.token_manager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'security.token_storage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'twig' => ['privates', 'twig', 'getTwigService', true],
        ], [
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'security.authorization_checker' => '?',
            'security.csrf.token_manager' => '?',
            'security.token_storage' => '?',
            'twig' => '?',
        ]))->withContext('Anunde\\Apps\\Api\\Controller\\LoginController', $container));

        return $instance;
    }
}
