<?php

namespace ContainerV9sJ9fF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikJwtAuthentication_JwtManagerService extends Anunde_Apps_Api_ApiKernelDevDebugContainer
{
    /**
     * Gets the public 'lexik_jwt_authentication.jwt_manager' shared service.
     *
     * @return \Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/lexik/jwt-authentication-bundle/Services/JWTTokenManagerInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/lexik/jwt-authentication-bundle/Services/JWTManager.php';
        include_once \dirname(__DIR__, 6).'/vendor/lexik/jwt-authentication-bundle/Services/PayloadEnrichmentInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/lexik/jwt-authentication-bundle/Services/PayloadEnrichment/ChainEnrichment.php';

        return $container->services['lexik_jwt_authentication.jwt_manager'] = new \Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager(($container->services['lexik_jwt_authentication.encoder'] ?? $container->load('getLexikJwtAuthentication_EncoderService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), 'username', new \Lexik\Bundle\JWTAuthenticationBundle\Services\PayloadEnrichment\ChainEnrichment([]));
    }
}
